import { describe, expect, it } from "vitest";
import fixture from "../../test/fixtures/real-execution/fixture.json";
import { REAL_EXECUTION_SAMPLE_PROBLEM } from "../../test/fixtures/real-execution/problem";
import { ProblemDefinitionSchema, validateProblemDefinition, type ProblemDefinition } from "../schema/problem";
import { hasBlockingError } from "../schema/issue";
import {
  toLekinpySystemPayload,
  fromLekinpyScheduleDict,
  type LekinpyScheduleDict,
} from "../adapter/translate";
import { computeMetrics } from "../scheduling/metrics";
import { ALGORITHM_REGISTRY, getAlgorithmDefinition } from "../registry/algorithms";
import type { Schedule } from "../schema/schedule";
import type { Metrics } from "../schema/schedule";

/**
 * Contract tests for the real-execution fixture (branch
 * test/real-execution-fixture). Every assertion here is checked against
 * `fixture.json`, which was generated by actually running the pinned
 * lekinpy v0.2.0 wheel (scripts/fixtures/generate-real-execution-fixture.ts)
 * — nothing in this file hand-writes an expected schedule.
 *
 * Regenerate/verify the fixture with:
 *   npm run fixture:generate   # overwrite
 *   npm run fixture:check      # verify without writing (used here as the
 *                               # "did the fixture drift from the pinned
 *                               # library" signal, run separately/in CI —
 *                               # this test file itself only reads the
 *                               # already-committed fixture, so it stays
 *                               # hermetic and fast, matching the existing
 *                               # test:unit convention).
 */

const ALGORITHM_IDS = ["fcfs", "spt", "edd", "wspt"] as const;

interface FixtureAlgorithmResult {
  libraryMetadata: { id: string; displayName: string; supportsMultiOperation: boolean; version: string };
  rawLekinpyScheduleDict: LekinpyScheduleDict;
  webSchedule: Schedule;
  metrics: Metrics;
}

const typedFixture = fixture as unknown as {
  provenance: {
    lekinLibraryTag: string;
    lekinLibraryCommit: string;
    lekinpyVersion: string;
    wheelSha256: string;
  };
  problem: ProblemDefinition;
  results: Record<(typeof ALGORITHM_IDS)[number], FixtureAlgorithmResult>;
};

describe("fixture provenance", () => {
  it("was generated from the pinned lekinpy v0.2.0 wheel, not an arbitrary install", () => {
    expect(typedFixture.provenance.lekinLibraryTag).toBe("v0.2.0");
    expect(typedFixture.provenance.lekinLibraryCommit).toBe("a3fee48");
    expect(typedFixture.provenance.lekinpyVersion).toBe("0.2.0");
    expect(typedFixture.provenance.wheelSha256).toMatch(/^[0-9a-f]{64}$/);
  });

  it("the fixture's problem matches the current sample ProblemDefinition source", () => {
    expect(typedFixture.problem).toEqual(REAL_EXECUTION_SAMPLE_PROBLEM);
  });
});

describe("ProblemDefinition -> lekinpy payload translation matches the real constructor shape", () => {
  it("every workcenter payload has exactly the fields lekinpy.Workcenter/Machine accept", () => {
    const payload = toLekinpySystemPayload(REAL_EXECUTION_SAMPLE_PROBLEM);
    for (const wc of payload.workcenters) {
      expect(Object.keys(wc).sort()).toEqual(["machines", "name", "release", "status"]);
      for (const machine of wc.machines) {
        expect(Object.keys(machine).sort()).toEqual(["name", "release", "status"]);
      }
    }
  });

  it("every job payload has exactly the fields lekinpy.Job/Operation accept (snake_case)", () => {
    const payload = toLekinpySystemPayload(REAL_EXECUTION_SAMPLE_PROBLEM);
    for (const job of payload.jobs) {
      expect(Object.keys(job).sort()).toEqual(["due", "job_id", "operations", "release", "rgb", "weight"]);
      for (const op of job.operations) {
        expect(Object.keys(op).sort()).toEqual(["processing_time", "status", "workcenter"]);
      }
    }
  });

  it("groups machines under their real workcenter, matching Workcenter(machines=[...]) nesting", () => {
    const payload = toLekinpySystemPayload(REAL_EXECUTION_SAMPLE_PROBLEM);
    const wc1 = payload.workcenters.find((w) => w.name === "WC1")!;
    expect(wc1.machines.map((m) => m.name).sort()).toEqual(["M1", "M1b"]);
  });
});

describe.each(ALGORITHM_IDS)("real execution invariants — %s", (algorithmId) => {
  const result = typedFixture.results[algorithmId];
  const schedule = result.webSchedule;
  const problem = typedFixture.problem;

  it("every operation appears exactly once across the whole schedule", () => {
    const expected = new Set<string>();
    for (const job of problem.jobs) {
      job.operations.forEach((_op, i) => expected.add(`${job.jobId}-O${i}`));
    }
    const actual: string[] = [];
    for (const ms of schedule.machines) {
      for (const op of ms.operations) actual.push(op.scheduledOperationId);
    }
    expect(new Set(actual).size).toBe(actual.length); // no duplicates
    expect(new Set(actual)).toEqual(expected); // exact coverage
  });

  it("job precedence is respected: operation i+1 never starts before operation i ends", () => {
    for (const job of problem.jobs) {
      const ops = schedule.machines
        .flatMap((ms) => ms.operations)
        .filter((op) => op.jobId === job.jobId)
        .sort((a, b) => a.operationIndex - b.operationIndex);
      for (let i = 0; i < ops.length - 1; i++) {
        expect(ops[i + 1]!.startTime).toBeGreaterThanOrEqual(ops[i]!.endTime);
      }
    }
  });

  it("machines never overlap operations", () => {
    for (const ms of schedule.machines) {
      const ordered = [...ms.operations].sort((a, b) => a.sequencePosition - b.sequencePosition);
      for (let i = 0; i < ordered.length - 1; i++) {
        expect(ordered[i + 1]!.startTime).toBeGreaterThanOrEqual(ordered[i]!.endTime);
      }
      // sequencePosition is contiguous 0..n-1, matching lekinpy's convention
      expect(ordered.map((op) => op.sequencePosition)).toEqual(ordered.map((_op, i) => i));
    }
  });

  it("machine and job release times are respected", () => {
    const releaseByMachine = new Map(problem.machines.map((m) => [m.machineId, m.release]));
    for (const ms of schedule.machines) {
      const machineRelease = releaseByMachine.get(ms.machineId) ?? 0;
      for (const op of ms.operations) {
        expect(op.startTime).toBeGreaterThanOrEqual(machineRelease);
      }
    }
    const releaseByJob = new Map(problem.jobs.map((j) => [j.jobId, j.release]));
    for (const ms of schedule.machines) {
      for (const op of ms.operations) {
        if (op.operationIndex === 0) {
          expect(op.startTime).toBeGreaterThanOrEqual(releaseByJob.get(op.jobId)!);
        }
      }
    }
  });

  it("operation duration equals processingTime", () => {
    const opById = new Map<string, number>();
    for (const job of problem.jobs) {
      job.operations.forEach((op) => opById.set(`${job.jobId}-O${op.operationIndex}`, op.processingTime));
    }
    for (const ms of schedule.machines) {
      for (const op of ms.operations) {
        expect(op.endTime - op.startTime).toBe(opById.get(op.scheduledOperationId));
      }
    }
  });
});

describe.each(ALGORITHM_IDS)("fromLekinpyScheduleDict() / computeMetrics() reproduce the stored fixture — %s", (algorithmId) => {
  const result = typedFixture.results[algorithmId];

  it("fromLekinpyScheduleDict() on the stored raw dict produces the stored webSchedule", () => {
    const recomputed = fromLekinpyScheduleDict(result.rawLekinpyScheduleDict, `fixture-${algorithmId}`, algorithmId);
    expect(recomputed).toEqual(result.webSchedule);
  });

  it("computeMetrics() on the stored webSchedule produces the stored metrics", () => {
    const recomputed = computeMetrics(result.webSchedule, typedFixture.problem);
    expect(recomputed).toEqual(result.metrics);
  });

  it("algorithm metadata matches the current registry", () => {
    const registryEntry = getAlgorithmDefinition(algorithmId);
    expect(registryEntry).toBeDefined();
    expect(result.libraryMetadata).toEqual(registryEntry!.libraryMetadata);
  });
});

describe("the fixture detects deliberate drift", () => {
  it("in schedule shape: a mutated raw dict no longer matches the stored webSchedule", () => {
    const result = typedFixture.results.fcfs;
    const mutated: LekinpyScheduleDict = JSON.parse(JSON.stringify(result.rawLekinpyScheduleDict));
    mutated.machines[0]!.operations[0]!.start_time += 1000; // inject drift
    const recomputed = fromLekinpyScheduleDict(mutated, "fixture-fcfs", "fcfs");
    expect(recomputed).not.toEqual(result.webSchedule);
  });

  it("in metrics: a mutated schedule no longer matches the stored metrics", () => {
    const result = typedFixture.results.fcfs;
    const mutatedSchedule: Schedule = JSON.parse(JSON.stringify(result.webSchedule));
    mutatedSchedule.machines[0]!.operations[0]!.endTime += 1000; // inject drift
    const recomputed = computeMetrics(mutatedSchedule, typedFixture.problem);
    expect(recomputed).not.toEqual(result.metrics);
  });

  it("in registry metadata: a mutated registry entry no longer matches the fixture's stored metadata", () => {
    const result = typedFixture.results.fcfs;
    const mutatedRegistryMetadata = { ...result.libraryMetadata, displayName: "Deliberately Wrong Name" };
    expect(mutatedRegistryMetadata).not.toEqual(result.libraryMetadata);
    // and the real registry (unmutated) still agrees with the fixture, proving
    // the check above is sensitive to real drift and not vacuously true:
    const registryEntry = getAlgorithmDefinition("fcfs")!;
    expect(registryEntry.libraryMetadata).toEqual(result.libraryMetadata);
  });
});

describe("JSON round-tripping preserves the validated schema", () => {
  it("the fixture's problem, round-tripped through JSON, is still schema-valid with zero errors", () => {
    const roundTripped = JSON.parse(JSON.stringify(typedFixture.problem));
    const parsed = ProblemDefinitionSchema.safeParse(roundTripped);
    expect(parsed.success).toBe(true);
    expect(hasBlockingError(validateProblemDefinition(roundTripped))).toBe(false);
  });

  it("every algorithm's webSchedule, round-tripped through JSON, is still well-typed for fromLekinpyScheduleDict/computeMetrics", () => {
    for (const algorithmId of ALGORITHM_IDS) {
      const result = typedFixture.results[algorithmId];
      const roundTripped: LekinpyScheduleDict = JSON.parse(JSON.stringify(result.rawLekinpyScheduleDict));
      expect(() => fromLekinpyScheduleDict(roundTripped, "rt", algorithmId)).not.toThrow();
      const schedule = fromLekinpyScheduleDict(roundTripped, "rt", algorithmId);
      expect(() => computeMetrics(schedule, typedFixture.problem)).not.toThrow();
    }
  });
});

describe("registry-wide sanity", () => {
  it("the fixture covers every algorithm currently in ALGORITHM_REGISTRY, and vice versa", () => {
    expect(new Set(Object.keys(typedFixture.results))).toEqual(new Set(ALGORITHM_REGISTRY.map((a) => a.id)));
    expect(new Set(ALGORITHM_IDS)).toEqual(new Set(ALGORITHM_REGISTRY.map((a) => a.id)));
  });
});
